services:
  user_auth_database:
    image: mongo:latest
    container_name: user-auth-database
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - user_auth_data:/data/user_auth_db/
    networks:
      - authnet
    command: mongod --quiet --logpath /dev/null 
  user_auth_service:
    build: .
    container_name: user-auth-backend
    depends_on:
      - user_auth_database
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/${MONGO_DB}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - authnet
volumes:
  user_auth_data:
    driver: local

networks:
  authnet:
    driver: bridge