FROM golang:1.24.1-alpine AS builder

WORKDIR /app

RUN apk add --no-cache protobuf git build-base

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV PATH="/root/go/bin:$PATH"

COPY . .
RUN go mod tidy

# Compile user.proto. the pb.go files will be generated in the "go_package = "user-auth/proto"" location
RUN protoc --go_out=. --go-grpc_out=. --proto_path=. proto/user.proto   

RUN go build -o /bin/user-auth ./main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /bin/user-auth ./

CMD ["./user-auth"]