services:
  sf_core_database:
    image: postgres:latest
    container_name: sf-core-database
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_USERNAME}
      - POSTGRES_USER=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_DB}
    volumes:
      - sf_core_data:/data/sf_core_db/
    networks:
      - corenet
  sf_core_service:
    build: .
    container_name: sf-core-backend
    depends_on:
      - sf_core_database
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - POSTGRES_URI=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_DB}/${POSTGRES_DB}
    networks:
      - corenet
volumes:
  sf_core_data:
    driver: local
networks:
  corenet:
    driver: bridge