FROM rust:1.85.1-slim AS builder

WORKDIR /app

# DEPENDENCY CACHING! (So no rebuilding dependencies again)
COPY ./Cargo.toml ./Cargo.lock ./
RUN mkdir -p src && echo 'fn main() {}' > src/main.rs

RUN cargo build --release
RUN cargo clean

# FINAL BUILD
COPY ./src ./src
COPY build.rs ./
COPY proto ./proto
RUN mkdir -p migrations

RUN cargo build --release

# PREVENT CHANING MIGRANTIONS AFFECTS CACHING
COPY ./migrations ./migrations

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/target/release/sf-core ./app

CMD ["./app"]