services:
  sf_core_database:
    image: postgres:latest
    container_name: sf-core-database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}
      - PGPORT=${DB_PORT}
    volumes:
      - sf_core_data:/data/sf_core_db/
    networks:
      - sfnet
  sf_core_service:
    build: .
    container_name: sf-core-backend
    depends_on:
      - sf_core_database
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - sfnet
volumes:
  sf_core_data:
    driver: local

networks:
  sfnet:
    driver: bridge