FROM rust:1.85.1-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev

# DEPENDENCY CACHING! (So no rebuilding dependencies again)
COPY ./Cargo.toml ./Cargo.lock ./
RUN mkdir -p src && echo 'fn main() {}' > src/main.rs

RUN cargo build --release
RUN cargo clean
RUN cargo install diesel_cli --no-default-features --features postgres

# FINAL BUILD
COPY ./src ./src

RUN cargo build --release


FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*

COPY ./migrations ./migrations
COPY --from=builder /usr/local/cargo/bin/diesel /usr/local/bin/diesel
COPY --from=builder /app/target/release/sf-core ./app

CMD ["sh", "-c", "diesel migration run && ./app"]