DROP TYPE IF EXISTS item_type CASCADE;
DROP TYPE IF EXISTS character_class CASCADE;
DROP TYPE IF EXISTS entity_type CASCADE;


DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS attributes CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS entities CASCADE;

DROP FUNCTION IF EXISTS add_new_item CASCADE;
DROP FUNCTION IF EXISTS add_new_character CASCADE;
DROP FUNCTION IF EXISTS add_new_user CASCADE;
